[[redirects]]
from = "/:any"
to = "https://docs.niuex.dev/:any"
status = 302
force = true

[[redirects]]
from = "/yinyunskin/:any"
to = "https://docs.niuex.dev/hokoisle-skin/:any"
status = 302
force = true
